{% set name = "h5sparse" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/h/h5sparse/h5sparse-{{ version }}.tar.gz"
  sha256: b7e6fbfa2f2f61adaa169a3a0a52bc6f2178f5daff8fa6d972a8dcaa7f3cc8f7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - numpy
  run:
    - six
    - h5py
    - numpy
    - python
    - scipy
    - nose
    - coverage


test:
  imports:
    - h5sparse

about:
  home: "https://github.com/appier/h5sparse"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Scipy sparse matrix in HDF5."
  doc_url: https://github.com/appier/h5sparse

extra:
  recipe-maintainers:
    - phlya
