{% set name = "coolpuppy" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.python.org/packages/source/c/coolpuppy/coolpuppy-{{ version }}.tar.gz"
  sha256: e9316a9748ce1ce4cf194bbe8777fb8f6c05a05ad9754ba7b71387e2f21cd8e5

build:
  number: 0
  entry_points:
    - coolpup.py = coolpuppy.CLI:main
    - plotpup.py = coolpuppy.plotpuppy_CLI:main
    - dividepups.py = coolpuppy.divide_pups_CLI:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - cython
    - pip
    - python
    - numpy
  run:
    - h5py >=3.0
    - h5sparse
    - bioframe >=0.3.3
    - cooler >=0.8.5
    - cooltools >=0.5.2
    - matplotlib-base
    - multiprocessing
    - numba
    - numpy >=1.16.5
    - pandas
    - python
    - scipy
    - pytables
    - more_itertools
    - seaborn
    - natsort
    - m2r2
    - multiprocessing_logging

test:
  imports:
    - coolpuppy
    - coolpuppy.coolpup
  commands:
    - coolpup.py --help
    - plotpup.py --help
    - dividepups.py --help

about:
  home: "https://github.com/open2c/coolpuppy"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A versatile tool to perform pile-up analysis on Hi-C data in .cool format "
  doc_url: https://coolpuppy.readthedocs.io

extra:
  recipe-maintainers:
    - phlya
